### ISSUE TITLE
# Bloque I

### ISSUE THREAD

**Issue by IoTeacher** [unidtj/redes#1]
Antecedentes Admin de Redes

**Comment by IoTeacher** [comment]
Inicamos con repaso de Git
Estado de la Maquina Virtual VM (virtualBox)
- uso de Tasksel (para el SSH remoto)
Conectarnos al servidor real.

1.1 Conocer servicios de Networking
https://help.ubuntu.com/lts/serverguide/network-configuration.html

**Comment by IoTeacher** [comment]
![screen shot 2018-05-19 at 8 54 22 am](https://user-images.githubusercontent.com/2523851/40270433-3fcd91b6-5b42-11e8-92d2-839fb4d3ff29.jpg)

Solo checar que este OpenSSH prendido

**Comment by IoTeacher** [comment]
# Ejercita comandos en la terminal para perder el miedo.
https://www.binarytides.com/linux-fun-commands/

**Comment by IoTeacher** [comment]
Creo que ya perdieron el miedo a la terminal.
![](https://cdn0.iconfinder.com/data/icons/cosmo-multimedia/40/terminal-512.png)

**Comment by almaflores** [comment]
no recuerdo mi usuario... 👎

**Comment by IoTeacher** [comment]
![](https://www.techbrown.com/wp-content/uploads/2016/11/ssh.png)
# SECURE SSH mas SEGURO

## ACTIVIDAD: Aplica la recomendación para "reforzar" los acceso SSH a su servidor.

https://medium.com/@mr_rigden/hardening-ssh-1bcb99cd4cef

  NOTAS:   _norton_ (es un usuario cambiarlo por el suyo)

**Comment by IoTeacher** [comment]
![screen shot 2018-05-19 at 10 06 20 am](https://user-images.githubusercontent.com/2523851/40271015-5d61af50-5b4c-11e8-89b6-e0939282efce.jpg)
![screen shot 2018-05-19 at 10 06 07 am](https://user-images.githubusercontent.com/2523851/40271016-5d87ae6c-5b4c-11e8-9dbb-e093042b37ba.jpg)
![screen shot 2018-05-19 at 10 05 57 am](https://user-images.githubusercontent.com/2523851/40271017-5da7e358-5b4c-11e8-9cf6-df8bb44f3561.jpg)
![screen shot 2018-05-19 at 10 05 47 am](https://user-images.githubusercontent.com/2523851/40271018-5dcb5428-5b4c-11e8-8f08-e4b8763147b3.jpg)

**Comment by MrAlonsoCervantes** [comment]
# COMANDOS PRACTICAS 

COWSAY, FIGLET, SL 

![captura de pantalla 2018-05-19 a la s 09 26 16](https://user-images.githubusercontent.com/33181759/40271240-5e4db672-5b4f-11e8-8a89-94d8caaf6c21.png)
![captura de pantalla 2018-05-19 a la s 09 25 43](https://user-images.githubusercontent.com/33181759/40271244-5fa792e0-5b4f-11e8-98f2-f3a04f20c23e.png)

**Comment by MrAlonsoCervantes** [comment]
FORTUNE 
![captura de pantalla 2018-05-19 a la s 10 32 02](https://user-images.githubusercontent.com/33181759/40271280-f48038a4-5b4f-11e8-8d4b-e5e37da847b3.png)

**Comment by cesar-vaquera** [comment]
## **_Practicando con comandos linux/ubuntu_**

**Comment by almaflores** [comment]
![123](https://user-images.githubusercontent.com/39222054/40271708-e075535c-5b55-11e8-9b69-5bcfb08f835f.png)

**Comment by anuartl** [comment]
Agregar usuario
![2018-05-19_113108](https://user-images.githubusercontent.com/33182290/40271851-3719d62c-5b58-11e8-92be-905a7c81ab1d.png)

**Comment by IoTeacher** [comment]
# Agregar usuarios y darles derechos
https://www.digitalocean.com/community/tutorials/how-to-add-and-delete-users-on-an-ubuntu-14-04-vps

**Comment by jmjackson** [comment]
![captura de pantalla 2018-05-19 a la s 12 02 11](https://user-images.githubusercontent.com/7651269/40272089-81757402-5b5c-11e8-948a-d3ea6d849047.png)

Autentication ssh Via google token

**Comment by almaflores** [comment]
![5](https://user-images.githubusercontent.com/39222054/40272121-445e6ef6-5b5d-11e8-85e7-1cf63c5706d2.png)

**Comment by Asened** [comment]
![captura de pantalla 2018-05-19 a la s 12 12 25](https://user-images.githubusercontent.com/33376670/40272162-52679742-5b5e-11e8-8686-99af4ee7fddf.png)

**Comment by almaflores** [comment]
![56](https://user-images.githubusercontent.com/39222054/40272311-19937600-5b60-11e8-9e56-2867be961aa9.png)

**Comment by almaflores** [comment]
![56](https://user-images.githubusercontent.com/39222054/40272319-2f93630c-5b60-11e8-8257-2099f8d7e399.png)

**Comment by LeonardoEnriquezA** [comment]
![capture](https://user-images.githubusercontent.com/7254035/40272384-2b5d4978-5b61-11e8-808c-b13a225805dd.JPG)

**Comment by Asened** [comment]
![captura de pantalla 2018-05-19 a la s 12 47 44](https://user-images.githubusercontent.com/33376670/40272497-e5995c5e-5b62-11e8-963b-8f0bda988a12.png)

**Comment by MrAlonsoCervantes** [comment]
# PRACTICA SSH AUDIT



![captura de pantalla 2018-05-19 a la s 12 50 11](https://user-images.githubusercontent.com/33181759/40272515-3e7d66ee-5b63-11e8-8c76-c469dc547c86.png)
