### ISSUE TITLE
2.1 MicroServicios

### ISSUE THREAD

**Issue by IoTeacher** [unidtj/redes#3]
Iniciamos la sesión con un repaso de comandos de consola, para la revisión de microservicios que instalaremos en nuestro servidor dedicado.

**Comment by IoTeacher** [comment]
Checar estos comandos en su VirtuaBox y de practicarlos en el servidor remoto **(no aplicar el comando numero 9 de shutdown porque apagarán el equipo)**

**Comment by IoTeacher** [comment]
## ¿Que son microservicios y defina Docker. ?

**Comment by IoTeacher** [comment]
# ¿Investigar que son los archivos con extension *.YALM

**Comment by Asened** [comment]
##  Que son microservicios
Los microservicios son una arquitectura y enfoque sobre la escritura de software en que las aplicaciones se dividen en componentes más pequeños e independiente entre si. A diferencia de un enfoque tradicional y monolitico sobre las aplicaciones, n el que todos  se crea en una pieza, los microservicios están separados y funcionan conjuntamente para llevar a cabo las mismas tareas, cada uno de estos componentes, o procesos son microservicios. Este enfoque sobre el desarrollo de software valora la granularidad por ser liviana y la capacidad de compartir el proceso similar en varias aplicaciones.


## Docker
La idea tras de Docker es crear contenedores ligeros y portables para las aplicaciones software que puedan ejecutarse en cualquier maquina con Docker instalado, independientemente del sistema operativo que la maquina tenga, facilitando los despliegues.
Docker es una herramienta diseñada podrá beneficiar a desarrolladores, testes como administradores del sistema, en relación  a las maquinas donde se ejecutan las aplicación de software, los procesos de despliegue etc.
En el caso de los desarrolladores  el uso de docker hace que puedan centrarse en desarrollar su código  sin preocuparse de si dicho código funcionara en la maquina en la que serà ejecutada.
Con testing tiene el entorno de pruebas.
Es muy sencillo crear y eliminar contenedores, son  muy ligeros por lo que se pueden ejecutar varios contenedores en a misma maquina.

**Comment by marixza2018** [comment]
![image](https://user-images.githubusercontent.com/39220230/40579273-86c4b2ac-60d8-11e8-827f-5db1a618566b.png)

**Comment by marixza2018** [comment]
![image](https://user-images.githubusercontent.com/39220230/40579297-13df7b68-60d9-11e8-90b5-9e446a3002ab.png)

![image](https://user-images.githubusercontent.com/39220230/40579309-71c3c2ac-60d9-11e8-84e8-63996c215ab4.png)

**Comment by Asened** [comment]
## .YAML
Es un formato de datos inspirado en lenguajes como XML, C, Python, Perl, así como el formato para correos electrónicos. 
Estos documentos se guardan en formato de texto plano y se anexan con la extensión .yml. serialización de datos eficiente era el principal objetivo de los desarrolladores del formato .yml, ya que permite a los usuarios crear .yml archivos con contenido independiente de cualquier lenguaje de marcas en particular. Estos archivos .yml también pueden ser leídos por cualquier editor de texto desarrollado para crear, abrir y editar archivos de texto sin formato, ya sea de texto Edición de software para sistemas basados ​​en Microsoft Windows como Microsoft WordPad y Microsoft Bloc de notas, o para plataformas Mac como el software de edición de textos de Apple. bibliotecas YAML también se pueden utilizar para integrar el formato YML en varios lenguajes de programación. Estos lenguajes de programación pueden ser Ruby, C / C ++, Python, Perl, PHP, Java, JavaScript, AJAX, C # y así sucesivamente. Por ejemplo, un archivo con la extensión .yml puede almacenar contenido y servir como un archivo de base de datos implementada con RoR (Ruby on Rails) funcionalidades de programación, y este archivo de base de datos puede ser utilizado para almacenar información sobre las conexiones de red cada vez que los usuarios intentan conectarse a una base de datos de red.

**Comment by almaflores** [comment]
**_`[# Que son microservicios](url)`_**

Un microservicio es un componente que puede ser desplegado, evolucionado y actualizado de forma independiente. Este componente encapsula la lógica necesaria para cubrir una funcionalidad completa, entendiendo por completa que incluye todas las capas necesarias para implementarla, desde el API hasta el acceso a la base de datos. En general, estas funcionalidades serán bastante pequeñas (de ahí lo de micro), y nuestra arquitectura se basará en tener un montón de componentes como éste comunicándose unos con otros mediante algún protocolo ligero. Lo más habitual es que la comunicación se realice mediante peticiones y respuestas HTTP, o algún bus de mensajes simple.

_________________________ . ___________________________._____________________________.___________________

**Comment by almaflores** [comment]
**# ¿Qué es Docker?**
La idea detrás de Docker es crear contenedores ligeros y portables para las aplicaciones software que puedan ejecutarse en cualquier máquina con Docker instalado, independientemente del sistema operativo que la máquina tenga por debajo, facilitando así también los despliegues.

¡Ala! Definición traducida de la documentación oficial, demasiada información en pocas frases, no me entero de nada. Bien, empecemos por lo primero ¿qué es un contenedor?

Este concepto ya es antiguo, y viene de Linux, pero por hacerte un símil con el mundo real, imagina en tu cabeza un contenedor de esos que suelen llevar los barcos de mercancías, que contiene distintos productos.

**Comment by jmjackson** [comment]
# Microservicios

Los microservicios son una arquitectura y un enfoque sobre la escritura de software en el que las aplicaciones se dividen en componentes más pequeños e independientes entre sí. A diferencia de un enfoque tradicional y monolítico sobre las aplicaciones, en el que todo se crea en una única pieza, los microservicios están separados y funcionan conjuntamente para llevar a cabo las mismas tareas. Cada uno de estos componentes, o procesos, son los microservicios. Este enfoque sobre el desarrollo de software valora la granularidad por ser liviana y la capacidad de compartir un proceso similar en varias aplicaciones.


No obstante, el mayor interrogante al respecto es por qué sería preferible utilizar una arquitectura basada en microservicios. En pocas palabras, el objetivo es entregar software de calidad más rápido. Aunque los microservicios son un medio para tal fin, se deben considerar otras cuestiones. Dividir las aplicaciones en microservicios no es suficiente; es necesario administrarlos, orquestarlos y gestionar los datos que crean y modifican.

----

# Docker

-   "Docker”, el software de TI, es una tecnología de creación de contenedores, que permite la creación y el uso de contenedores de  [Linux®](https://www.redhat.com/es/topics/containers).
-   La  [comunidad Docker de open source](https://forums.docker.com/)  trabaja para mejorar estas tecnologías a fin de beneficiar a todos los usuarios de forma gratuita.
-   La empresa,  [Docker Inc.](https://www.docker.com/), desarrolla el trabajo de la comunidad Docker, lo hace más seguro y comparte estos avances con la comunidad más amplia. También respalda las tecnologías mejoradas y reforzadas para clientes empresariales.

Con DOCKER, puede considerar los contenedores como máquinas virtuales extremadamente livianas y modulares. Y obtiene flexibilidad con estos contenedores, que puede crear, implementar, copiar y mover de un entorno a otro.

----

# .YAML

YAML es un formato para guardar objetos de datos con estructura de árbol. Sus siglas significan YAML Ain't Markup Language (YAML no es otro lenguaje de marcado).

Este lenguaje es muy legible para las personas, más legible que JSON y sobretodo que XML.

Normalmente se utiliza para definir archivos de configuración, aunque también es posible serializar objetos, es decir, escribir la estructura de un objeto en modo cadena de texto para posteriormente poderlo recuperar. Sin embargo, para este propósito es bastante más lento que utilizar JSON.

Hay librerías para todos los lenguajes de programación, desde Ruby, PHP, Java hasta C# entre otros.

**Comment by LeonardoEnriquezA** [comment]
# Microservicios!

**Los microservicios** son una arquitectura y un enfoque sobre la escriura de software en el que las aplicaciones se dividen en componentes mas pequeños e independientes entre si. A diferencia de un enfoque tradicional y monolitico sobre las aplicaciones, en el que todo se crea en una unica pieza, los microservicios estan separados y funcionan conuntamente para llevar a cabo las mismas tareas. Cada uno de estos componenetes, o procesos, son los **microservicios**.

El objetivo es entregar software de calida mas rapido, aunque los microservicios son un medio para tal fin, se deben considerar otras cuestiones. Dividir las apicaciones en microservicios no es suficiente; es necesario administrarlos, orquestarlos y gestionar los datos que crean y modifican.

***
# Docker!

- Docker, es una tecnologia de creacion de contenedores, que permite la creacion y el uso de contenedores de ligeros y portables para las aplicaciones software que puedan ejecutarse en cualquier maquina con Docker instalado, independientemente del sistema operativo que la maquina tenga por debajo, facilitando asi tambien los despliegues.
- Docker, es una herramienta diseñada para beneficiar tanto a desarrolladores, testers, administradores de sistemas, en relacion a las maquinas, a los entornos en si donde se ejecuten las aplicaciones software, los procesos de despliegue, etc.
- Un contenedor Docker no es lo mismo que una maquina virtual. Un contenedor es mas ligero, ya que mientras que una maquina virtual necesita instalarle un sistema operativo para funcionar, un contenedeor Docker funciona utilizando el sistema operativo que tiene la maquina en la que se ejecuta el contenedor.
