### ISSUE TITLE
Practica bloque 2

### ISSUE THREAD

**Issue by marixza2018** [unidtj/redes#4]
![image](https://user-images.githubusercontent.com/39220230/40578079-960a3e00-60c2-11e8-9fba-4acba66d4565.png)

**Comment by almaflores** [comment]
# **docker run hello-world**

![1](https://user-images.githubusercontent.com/39222054/40579127-b926a6f4-60d5-11e8-8578-9031bd1fdafb.png)

**Comment by almaflores** [comment]
**Hola Mundo en Contenedor # alpine**
![4](https://user-images.githubusercontent.com/39222054/40579174-a4a7f588-60d6-11e8-82c9-7231a2842744.png)

**Comment by marixza2018** [comment]
docker stop  y el docker rm 
![image](https://user-images.githubusercontent.com/39220230/40579230-a6eaa9fc-60d7-11e8-9cf0-7c67e5906b20.png)

**Comment by almaflores** [comment]
**_# docker container ls -a_**

![6](https://user-images.githubusercontent.com/39222054/40579233-af37cfea-60d7-11e8-9bea-2778717aa417.png)

**Comment by jmjackson** [comment]
# docker run hello-world
![captura de pantalla 2018-05-26 a la s 11 29 37](https://user-images.githubusercontent.com/7651269/40579261-53b54c8c-60d8-11e8-8639-65869a4bc745.png)

**Comment by jmjackson** [comment]
# alpine install 

![captura de pantalla 2018-05-26 a la s 11 36 21](https://user-images.githubusercontent.com/7651269/40579305-59dc1d7e-60d9-11e8-9ae2-f5b2c8de7c39.png)

**Comment by Asened** [comment]
## docker run
![captura de pantalla 2018-05-26 a la s 11 43 50](https://user-images.githubusercontent.com/33376670/40579339-2a4b4368-60da-11e8-880b-dcfaf9c05390.png)

**Comment by Asened** [comment]
## alpine

![captura de pantalla 2018-05-26 a la s 11 46 41](https://user-images.githubusercontent.com/33376670/40579367-ac80b264-60da-11e8-89b0-bd68e8fd6c0f.png)

**Comment by Asened** [comment]
![captura de pantalla 2018-05-26 a la s 11 49 42](https://user-images.githubusercontent.com/33376670/40579386-0f1c7f7a-60db-11e8-8361-2f13766ac396.png)

**Comment by almaflores** [comment]
> #  _**docker run docker/whalesay cowsay boo**_

![8](https://user-images.githubusercontent.com/39222054/40579407-8cc43a76-60db-11e8-98ca-e88773b5d703.png)

**Comment by LeonardoEnriquezA** [comment]
**Docker run hello-world con windows PowerShell 
![image](https://user-images.githubusercontent.com/7254035/40681432-ed5b38bc-633d-11e8-98bf-39ca36e4e8aa.png)
