### ISSUE TITLE
B2.2 Docker Networking, trabajando con el Bridge (puente)

### ISSUE THREAD

**Issue by IoTeacher** [unidtj/redes#5]
<img width="878" alt="docker" src="https://user-images.githubusercontent.com/2523851/40877573-0ad091b0-6638-11e8-9e78-177a2b50bc4b.png">

**Comment by IoTeacher** [comment]
Colaborativamente organiza el grupo para armar el marco teórico de:

Administrando imágenes de DOCKER
Volumenes en docker (para respaldos, extracción fuera del Docker, etc.)
Básicos de Redes del Docker
Archivos de configuración (Componse YALM)
     ¿Que es un archivo tipo YALM (*.YLM) ?

**Comment by LeonardoEnriquezA** [comment]
https://www.digitalocean.com/community/tutorials/como-instalar-y-usar-docker-en-ubuntu-16-04-es

**Comment by LeonardoEnriquezA** [comment]
![image](https://user-images.githubusercontent.com/7254035/40879128-244cfed6-6650-11e8-8896-f99d63a716f2.png)

**Comment by LeonardoEnriquezA** [comment]
**Imagen hello-world
Imagen ubuntu**
![image](https://user-images.githubusercontent.com/7254035/40879198-46ecfc24-6651-11e8-8997-483b73e5653d.png)

**Comment by almaflores** [comment]
**# Instalación de Docker** 

![1d](https://user-images.githubusercontent.com/39222054/40879231-e0fd102e-6651-11e8-943f-a20f5d03e1b7.png)

**Comment by MrAlonsoCervantes** [comment]
# Algunos Comandos de Docker

https://www.danielcastanera.com/comandos-utiles-en-docker/

**Comment by cesar-vaquera** [comment]
# **Instalar Docker para Ubuntu**

## (1) Instalar repositorio de Docker
$ sudo apt-get update
$ sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
$ sudo apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
$ sudo apt-get update
$ apt-cache policy docker-engine
![aptcache](https://user-images.githubusercontent.com/33182332/40879674-635d2c60-6658-11e8-81e9-fd0db9f67c2b.JPG)

## (2) Instalar  Docker CE

$ sudo apt-get install -y docker-engine
$ sudo systemctl status docker
![aptcache2](https://user-images.githubusercontent.com/33182332/40879704-bfc967f2-6658-11e8-9698-3a5d4858fab7.JPG)

## (3) Veriicando la instalacion

$ sudo docker run hello-world
![hello](https://user-images.githubusercontent.com/33182332/40879726-0643f56c-6659-11e8-94e2-aa6203ca78a3.JPG)

**Comment by Asened** [comment]
## docker images
![captura de pantalla 2018-06-02 a la s 11 36 09](https://user-images.githubusercontent.com/33376670/40879742-60f14b86-6659-11e8-92d2-a36c46162644.png)

**Comment by almaflores** [comment]
**# sudo docker images**
![2b](https://user-images.githubusercontent.com/39222054/40879750-7ca6a1d2-6659-11e8-850a-65b3f8f25cb4.png)

**Comment by almaflores** [comment]
**# Bienvenido a nginx!**

![2f](https://user-images.githubusercontent.com/39222054/40879819-0b8053f2-665b-11e8-8109-bc914221924a.png)

**Comment by Asened** [comment]
## sudo docker run --name docker-nginx -p 80:80 -d nginx
![captura de pantalla 2018-06-02 a la s 11 49 34](https://user-images.githubusercontent.com/33376670/40879843-8362e696-665b-11e8-91a1-63b08f291847.png)

**Comment by Asened** [comment]
## IP PUBLICA
![captura de pantalla 2018-06-02 a la s 11 55 49](https://user-images.githubusercontent.com/33376670/40879860-fccacd82-665b-11e8-817f-891ecda9a696.png)

**Comment by MrAlonsoCervantes** [comment]
# DOCKER NGINX 

![captura de pantalla 2018-06-02 a la s 11 47 29](https://user-images.githubusercontent.com/33181759/40879864-0c44ae72-665c-11e8-9ff9-159fdcd6abe5.png)

**Comment by MrAlonsoCervantes** [comment]
#DOCKER PULL LIBRERIAS

![captura de pantalla 2018-06-02 a la s 11 04 15](https://user-images.githubusercontent.com/33181759/40879885-5c77fbb0-665c-11e8-91a5-63f024c868c9.png)

**Comment by almaflores** [comment]
![captura de pantalla 2018-06-02 a la s 12 04 05](https://user-images.githubusercontent.com/39222054/40879930-1550a72c-665d-11e8-9a31-42a8fd994ac6.png)

**Comment by almaflores** [comment]
![captura de pantalla 2018-06-02 a la s 12 04 05](https://user-images.githubusercontent.com/39222054/40879937-3201c36a-665d-11e8-929b-6fa0e801dfa6.png)

**Comment by Asened** [comment]
##docker run hello-world
![captura de pantalla 2018-06-02 a la s 12 15 10](https://user-images.githubusercontent.com/33376670/40880024-c577caee-665e-11e8-8954-7b9f89e55cd6.png)

**Comment by MrAlonsoCervantes** [comment]
# START/STOP PROCESOS WITH DOCKER

![stop start process docker](https://user-images.githubusercontent.com/33181759/40880039-e4652870-665e-11e8-83dc-e8a0d9e12d2d.png)

**Comment by marixza2018** [comment]
![image](https://user-images.githubusercontent.com/39220230/40880144-821607be-6660-11e8-9d0f-06f13408ffee.png)

![image](https://user-images.githubusercontent.com/39220230/40880171-dc93f566-6660-11e8-8ebc-d80d39a89f35.png)
![image](https://user-images.githubusercontent.com/39220230/40880177-e64a2544-6660-11e8-9318-86a595852b0c.png)

**Comment by jmjackson** [comment]
## Commit

![captura de pantalla 2018-06-02 a las 12 28 29](https://user-images.githubusercontent.com/7651269/40880143-80d8bb8a-6660-11e8-9d05-8325446e3b36.png)

**Comment by LeonardoEnriquezA** [comment]
![image](https://user-images.githubusercontent.com/7254035/41194973-8d2bf4e6-6bd9-11e8-9374-0faf9a770fe1.png)

![image](https://user-images.githubusercontent.com/7254035/41194981-b9df92ea-6bd9-11e8-970d-20c9014b9a53.png)

**Comment by marixza2018** [comment]
![img_20180609_083943](https://user-images.githubusercontent.com/39220230/41812212-e9832a5c-76d3-11e8-8f10-4fedd3283595.jpg)
![img_20180609_083947](https://user-images.githubusercontent.com/39220230/41812214-eb1b8198-76d3-11e8-80a2-43a6c8031ffc.jpg)
![img_20180609_083951](https://user-images.githubusercontent.com/39220230/41812215-ec8dce82-76d3-11e8-887e-048b512f758b.jpg)
![img_20180609_083959](https://user-images.githubusercontent.com/39220230/41812216-edc99740-76d3-11e8-9e66-464371d1746b.jpg)
![img_20180609_084008](https://user-images.githubusercontent.com/39220230/41812218-eed2017c-76d3-11e8-9524-d86be257bbdc.jpg)
![img_20180609_084024](https://user-images.githubusercontent.com/39220230/41812220-efddeedc-76d3-11e8-8be5-6999dda2ef59.jpg)
![img_20180609_084035](https://user-images.githubusercontent.com/39220230/41812222-f0fdb34c-76d3-11e8-9008-22e8d60289a7.jpg)
![img_20180609_084051](https://user-images.githubusercontent.com/39220230/41812223-f2b672f0-76d3-11e8-9330-64744a93977c.jpg)
