### ISSUE TITLE
Ejercicios de Linux unos 20/30 min.

### ISSUE THREAD

**Issue by IoTeacher** [unidtj/redes#6]
# Seleccionar su Servidor de practicas a Dockerizar
![screen shot 2018-06-02 at 9 26 43 am](https://user-images.githubusercontent.com/2523851/40878501-20d16b88-6647-11e8-8fc0-e763097bb62c.jpg)

# Como nos conectamos es via Linux 
## Descargar el *.pem
$ chmod 400 llavesita.pem
$ ssh -i llavesita.pem ubuntu@IP_QUE_LES_TOCO

# En Windows XP-10pro
### Descargar PUTTY Version completa (ocupamos el PuttyGEN)

![screen shot 2018-06-02 at 8 53 51 am](https://user-images.githubusercontent.com/2523851/40878509-3704596a-6647-11e8-8f3f-d925c3969e1b.jpg)
![screen shot 2018-06-02 at 9 24 33 am](https://user-images.githubusercontent.com/2523851/40878512-3f09a7a0-6647-11e8-8a07-543af038fdd3.jpg)
![screen shot 2018-06-02 at 9 25 30 am](https://user-images.githubusercontent.com/2523851/40878517-4c6e8b36-6647-11e8-8a42-354114efae2b.jpg)
![screen shot 2018-06-02 at 9 23 56 am](https://user-images.githubusercontent.com/2523851/40878520-5b53b2fc-6647-11e8-9402-088299e417d9.jpg)

**Comment by IoTeacher** [comment]
![img_3019-1](https://user-images.githubusercontent.com/2523851/40877737-cbd18002-663a-11e8-9509-3542e1f493ba.JPG)
![img_3016](https://user-images.githubusercontent.com/2523851/40877738-ce916c6c-663a-11e8-9b91-caf923b1aa60.JPG)
![img_3017](https://user-images.githubusercontent.com/2523851/40877739-cef02a54-663a-11e8-8432-97ace5d984a7.JPG)
![img_3018](https://user-images.githubusercontent.com/2523851/40877740-cf2c646a-663a-11e8-82d2-8b050266740c.JPG)
![img_3020](https://user-images.githubusercontent.com/2523851/40877742-d3016fae-663a-11e8-8a6f-3a62377e0ef9.JPG)
![img_3021](https://user-images.githubusercontent.com/2523851/40877743-d3315688-663a-11e8-9001-41f32275d116.JPG)
![img_3022](https://user-images.githubusercontent.com/2523851/40877744-d361b314-663a-11e8-8049-9901d83e9a0d.JPG)
![img_3024](https://user-images.githubusercontent.com/2523851/40877745-d39f94ea-663a-11e8-9efb-01a33ca06a46.JPG)
![img_3025](https://user-images.githubusercontent.com/2523851/40877746-d3e38e0c-663a-11e8-96af-a320af0ec4be.JPG)
![img_3026](https://user-images.githubusercontent.com/2523851/40877747-d431ebc4-663a-11e8-80d1-f32fe20a50ca.JPG)
![img_3027](https://user-images.githubusercontent.com/2523851/40877748-d49b1004-663a-11e8-800e-761e17445ccd.JPG)
![img_3028](https://user-images.githubusercontent.com/2523851/40877749-d4c05e72-663a-11e8-8dd7-fb0250d8478f.JPG)
![img_3029](https://user-images.githubusercontent.com/2523851/40877750-d4e1f5b4-663a-11e8-8285-f321bdbd1679.JPG)
![img_3030](https://user-images.githubusercontent.com/2523851/40877751-d5103e6a-663a-11e8-80aa-b09ccd7aa87d.JPG)
![img_3031](https://user-images.githubusercontent.com/2523851/40877752-d54c7de4-663a-11e8-93e9-d742679f29e5.JPG)
![img_3032](https://user-images.githubusercontent.com/2523851/40877753-d5869592-663a-11e8-9f3e-bfc509898525.JPG)
![img_3033](https://user-images.githubusercontent.com/2523851/40877754-d5b424e4-663a-11e8-9df0-79fee5556d2f.JPG)
![img_3034](https://user-images.githubusercontent.com/2523851/40877755-d5f27398-663a-11e8-9757-289d6377e9ac.JPG)
![img_3035](https://user-images.githubusercontent.com/2523851/40877756-d63d8f4a-663a-11e8-95b5-f3ccd4f9d00a.JPG)
![img_3036](https://user-images.githubusercontent.com/2523851/40877757-d6861b0c-663a-11e8-98bd-b5ef6bfd9256.JPG)
![img_3037](https://user-images.githubusercontent.com/2523851/40877758-d6f51e1c-663a-11e8-9aba-eecfa81008a2.JPG)
![img_3038](https://user-images.githubusercontent.com/2523851/40877759-d72aea7e-663a-11e8-8d27-cec5ccf11ed7.JPG)

**Comment by marixza2018** [comment]
Practica AWS, instalacion de puttygen, importancion de llave
![image](https://user-images.githubusercontent.com/39220230/40878226-c1befc0e-6642-11e8-92f3-e9ba9917bf84.png)

**Comment by marixza2018** [comment]
![image](https://user-images.githubusercontent.com/39220230/40878508-332381ae-6647-11e8-9755-600ac087a831.png)

**Comment by jmjackson** [comment]
## Connect to 54.205.236.243

![captura de pantalla 2018-06-02 a las 9 24 45](https://user-images.githubusercontent.com/7651269/40878503-26632cd0-6647-11e8-9a80-14715a67e475.png)

**Comment by Asened** [comment]
## Connect to 52.72.225.13
![captura de pantalla 2018-06-02 a la s 09 24 47](https://user-images.githubusercontent.com/33376670/40878511-3cfa97a8-6647-11e8-9a1c-83b9752630b6.png)

**Comment by LeonardoEnriquezA** [comment]
![image](https://user-images.githubusercontent.com/7254035/40878618-51723ec4-6648-11e8-8195-0e855eb6e546.png)

**Comment by LeonardoEnriquezA** [comment]
**$Sudo update
 $Sudo upgrade**
![image](https://user-images.githubusercontent.com/7254035/40878652-b5260fb8-6648-11e8-9f5a-a64614cb7d26.png)

**Comment by almaflores** [comment]
![1a](https://user-images.githubusercontent.com/39222054/40878910-01a57bfe-664d-11e8-9a82-0942a6ec5982.png)

**Comment by almaflores** [comment]
![1b](https://user-images.githubusercontent.com/39222054/40879111-0cca83f0-6650-11e8-8b81-0c9ba4661a35.png)

**Comment by Asened** [comment]
## install docker
![captura de pantalla 2018-06-02 a la s 10 44 30](https://user-images.githubusercontent.com/33376670/40879243-1612496e-6652-11e8-9c8a-d159c2bc490a.png)

**Comment by Asened** [comment]
## docker run hola-mundo
![captura de pantalla 2018-06-02 a la s 10 58 25](https://user-images.githubusercontent.com/33376670/40879398-f8388e10-6653-11e8-8146-4c241caec31e.png)

**Comment by cesar-vaquera** [comment]
# **Creando llave  PPK SSH en Windows**  

## **1.-) Abrir PuTTY Key Generator.**
![puttygen](https://user-images.githubusercontent.com/33182332/40879348-46cdb45c-6653-11e8-8bda-4f6b37fc9efe.jpg)

## **2.-) Seleccionar "Load" para cargar el archivo .PEM**
![puttygen2](https://user-images.githubusercontent.com/33182332/40879350-4ecd1120-6653-11e8-902b-12d4e89e8013.JPG)

## **3.-) Salvar como llave Privada**
![puttygen3](https://user-images.githubusercontent.com/33182332/40879352-5578c596-6653-11e8-8155-fa6c527aefbb.jpg)

# **Conectarse al Servidor** 
## **1.-) Abrir PuTTY Configuration**
## **2.-) Escribir la direccion IP del Servidor**
![server1](https://user-images.githubusercontent.com/33182332/40879373-bfeb4aca-6653-11e8-935e-0683c7db3389.JPG)

## **3.-) Cargar la llave PPK en Auth (Conexion>>SSH>>Auth)**
## **4.-) presionar Open**
![server2](https://user-images.githubusercontent.com/33182332/40879390-e67d99cc-6653-11e8-96b7-cff2770b512c.JPG)


## **5.-) Escribir nombre del usuario**
![server3](https://user-images.githubusercontent.com/33182332/40879396-f6eb2086-6653-11e8-85f3-6459c1fd0335.JPG)

## **6.-) Conexion establecida**
![server4](https://user-images.githubusercontent.com/33182332/40879399-fd3999fe-6653-11e8-94b3-b6478e3e8729.JPG)
