### ISSUE TITLE
Repaso semana 16 de junio

### ISSUE THREAD

**Issue by jmjackson** [unidtj/redes#7]

**Comment by jmjackson** [comment]
![captura de pantalla 2018-06-16 a las 8 34 17](https://user-images.githubusercontent.com/7651269/41500071-3079f466-7140-11e8-9c81-b2f6c9cd2eee.png)

**Comment by IoTeacher** [comment]
Para enviar un proceso al "Background" terminar el comando con "&"

**_$ sudo apt update & apt upgrade -y_**

**Comment by IoTeacher** [comment]
# Docker con MYSQL por favor 

De existir un "Dockerfile" esta nos ahorra mucho tiempo.
https://github.com/mysql/mysql-docker

**Comment by IoTeacher** [comment]
## CREAR UN ARCHIVO CON EL NANO. DE NOMBRE "dockerunid.sh" y copiar este contenido

```
echo ··· Script de instalar Actualizar e instalar Docker
sudo apt update & apt upgrade -y
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
sudo apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
sudo apt upgrade -y
apt-cache policy docker-engine
sudo apt-get install -y docker-engine
sudo systemctl status docker
sudo usermod -aG docker $(whoami)
docker run hello-world

```


Ahora darle permisos de ejecución
**$chmod +x dockerunid.sh**

Y ejecutarlo dentro del AWS Servidor
**$  ./dockerunid.sh**   (si lleva un punto y diagonal, asi se corren los "Bash" Scripts)

**Comment by IoTeacher** [comment]
# MYSQL

## Instalar MySQL
$ sudo docker pull mysql/mysql-server
$ sudo docker run --name=**mysqlUnid** -d mysql/mysql-server

# Ejecutar 
$ sudo docker run --name unidBDatos -e MYSQL_ROOT_PASSWORD=!Unid123 -d mysql

**Comment by LeonardoEnriquezA** [comment]
![image](https://user-images.githubusercontent.com/7254035/41500660-e7b39dda-714a-11e8-8989-aa2fb4584f41.png)

**Comment by almaflores** [comment]
![captura de pantalla 2018-06-16 a la s 10 45 38](https://user-images.githubusercontent.com/39222054/41501115-e99c5094-7152-11e8-96ce-30ef3e962ae8.png)

**Comment by almaflores** [comment]
![captura de pantalla 2018-06-16 a la s 11 04 14](https://user-images.githubusercontent.com/39222054/41501216-11d9a44c-7155-11e8-8b57-323b5e57bdab.png)
