### ISSUE TITLE
Firewall

### ISSUE THREAD

**Issue by IoTeacher** [unidtj/redes#8]
# FIREWALL

![screen shot 2018-06-16 at 11 35 07 am](https://user-images.githubusercontent.com/2523851/41501453-79f4526c-7159-11e8-9e28-e4ad64e1e719.jpg)

**Comment by IoTeacher** [comment]
# CONOCIENDO FIREWALL POPULARES BASADOS EN SOFTWARE LINUX

**Comment by IoTeacher** [comment]
#
![screen shot 2018-06-16 at 11 38 23 am](https://user-images.githubusercontent.com/2523851/41501475-cfb49bb2-7159-11e8-9786-c84a65ca4b67.jpg)

![screen shot 2018-06-16 at 11 25 14 am](https://user-images.githubusercontent.com/2523851/41501477-d63a3672-7159-11e8-9169-8e977bee626f.jpg)

**Comment by IoTeacher** [comment]
![screen shot 2018-06-16 at 11 43 27 am](https://user-images.githubusercontent.com/2523851/41501507-946a074e-715a-11e8-88d5-77e084c7f196.jpg)
![screen shot 2018-06-16 at 11 42 51 am](https://user-images.githubusercontent.com/2523851/41501508-948b1b1e-715a-11e8-977a-eb28f13743f3.jpg)
![screen shot 2018-06-16 at 11 41 18 am](https://user-images.githubusercontent.com/2523851/41501509-94abcf94-715a-11e8-99b3-6652a366111b.jpg)
![screen shot 2018-06-16 at 11 41 11 am](https://user-images.githubusercontent.com/2523851/41501510-94ca267e-715a-11e8-9333-a515561b8a3b.jpg)
![screen shot 2018-06-16 at 11 40 53 am](https://user-images.githubusercontent.com/2523851/41501511-94e8d9de-715a-11e8-88cd-19a0fcb20348.jpg)

**Comment by IoTeacher** [comment]
Creo que hay un BUG porque como es virtual no hardware hay que saltar el registro

https://www.clearos.com/clearfoundation/social/community/unable-to-finnish-system-registration,-error,-match-not-found-in-file

**Comment by IoTeacher** [comment]
### Para acceder a el SSH se pone

# $ ssh root@IP


![screen shot 2018-06-16 at 12 15 47 pm](https://user-images.githubusercontent.com/2523851/41501739-09c15534-715f-11e8-8ffd-bb5beb554065.jpg)

**Comment by jmjackson** [comment]
ClearOs
![captura de pantalla 2018-06-16 a las 12 26 51](https://user-images.githubusercontent.com/7651269/41501843-f3cf518e-7160-11e8-9b0b-998d0ecefb62.png)

**Comment by jmjackson** [comment]
Clear Os 2
![captura de pantalla 2018-06-16 a las 12 28 09](https://user-images.githubusercontent.com/7651269/41501847-ff740d04-7160-11e8-9d20-fe89e639f331.png)
