### ISSUE TITLE
Dia 23-junio

### ISSUE THREAD

**Issue by IoTeacher** [unidtj/redes#9]
Goool
![screen shot 2018-06-23 at 10 36 53 am](https://user-images.githubusercontent.com/2523851/41812109-841a7bae-76d1-11e8-91ab-2234f54d2813.jpg)

**Comment by anuartl** [comment]
Para instalar MySQL https://www.digitalocean.com/community/tutorials/how-to-install-mysql-on-ubuntu-16-04

**Comment by marixza2018** [comment]
![image](https://user-images.githubusercontent.com/39220230/41812177-0ca9055c-76d3-11e8-8973-693729281b46.png)
![image](https://user-images.githubusercontent.com/39220230/41812180-18bbfb6a-76d3-11e8-80f2-57db16ffc8eb.png)

**Comment by jmjackson** [comment]
# Mysql
![captura de pantalla 2018-06-23 a las 11 12 18](https://user-images.githubusercontent.com/7651269/41812361-61a571f0-76d6-11e8-8f9f-fdbea5424f5b.png)

# In Docker
![captura de pantalla 2018-06-23 a las 11 13 17](https://user-images.githubusercontent.com/7651269/41812370-771e8936-76d6-11e8-8fbb-518e80d40962.png)

**Comment by almaflores** [comment]
MYSQL


![captura de pantalla 2018-06-16 a la s 11 04 14](https://user-images.githubusercontent.com/39222054/41812528-582d94e2-76d9-11e8-9255-2991a5bc72c2.png)

**Comment by cesar-vaquera** [comment]
![captura](https://user-images.githubusercontent.com/33182332/41812577-77820430-76da-11e8-81ed-bd131209b561.JPG)

**Comment by MrAlonsoCervantes** [comment]
ubuntu@ip-172-31-28-6:~$ git clone https://github.com/datacharmer/test_db
Cloning into 'test_db'...
remote: Counting objects: 102, done.
remote: Total 102 (delta 0), reused 0 (delta 0), pack-reused 102
Receiving objects: 100% (102/102), 68.81 MiB | 27.75 MiB/s, done.
Resolving deltas: 100% (54/54), done.
Checking connectivity... done.


PARA RESTAURAR EL RESPALDO 


# Backup
docker exec CONTAINER /usr/bin/mysqldump -u root --password=root DATABASE > backup.sql

# Restore
cat backup.sql | docker exec -i CONTAINER /usr/bin/mysql -u root --password=root DATABASE

**Comment by LeonardoEnriquezA** [comment]
![image](https://user-images.githubusercontent.com/7254035/41812759-c9cd57d2-76dd-11e8-9853-c8b9ed76160d.png)

**Comment by MrAlonsoCervantes** [comment]
### PRACTICAS 

![captura de pantalla 2018-06-23 a la s 11 10 30](https://user-images.githubusercontent.com/33181759/41813138-fcd2a59a-76e4-11e8-9224-9f5692fe0dfb.png)
![captura de pantalla 2018-06-23 a la s 11 10 48](https://user-images.githubusercontent.com/33181759/41813139-fcf105da-76e4-11e8-983a-9f10397bda3f.png)
![captura de pantalla 2018-06-23 a la s 11 11 21](https://user-images.githubusercontent.com/33181759/41813140-fd159d3c-76e4-11e8-95f1-23a37c89870b.png)

**Comment by MrAlonsoCervantes** [comment]
**REMOVE COMMANDS**

![captura de pantalla 2018-06-23 a la s 11 35 17](https://user-images.githubusercontent.com/33181759/41813152-3e21d372-76e5-11e8-977e-ba8239b5255c.png)
